### 変数定義
@baseUrl = http://localhost:5000/api/v1

### ユーザログイン
### 1. ユーザがログインする
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username": "newuser",
    "email": "sample@example.com",
    "password": "Password123!"
}

### 2. 存在しないユーザでログインする
POST {{baseUrl}}/auth/login
Content-Type: application/json

{"username": "nonexistentuser", "password": "Password123!"}